#!/bin/bash

src_dir=$HOME/workbench/wifi-vehicles/data-collection/

if [ $# -lt 2 ]
then
	echo "usage : $0 <trace-nr> <wlan-iface>"
	echo "options : "
	echo "    <trace-nr> : nr. of trace to use in logs. 3 digit number w/ leading zeroes, e.g.: '041'"
	echo "    <wlan-iface> : name of wlan interface"
	exit 1
fi

# get comm. iface channel & width
channel=$(iw dev $2 info | awk '/channel/ {print $2}')
bw=$(iw dev $2 info | awk '/channel/ {print $6}')
# create output dir (if not available already)
output_dir=$HOME/workbench/sandbox/wardrive/trace-$1
mkdir -p "$output_dir"

# start the scan loop
python $src_dir/scan-loop.py --monitor-iface $2 --channel-list '1:20,6:20,36:40+' --output-dir "$output_dir" &
# log channel utilization
$src_dir/get-cbt.sh $1 "$output_dir" $2 &
# start gps logging script
python $src_dir/get-gps.py --output-dir "$output_dir" &
# extract cpu stats
$src_dir/get-cpu.sh $1 "$output_dir" &

exit 0
